services:
    php-up-edi:
        image: up-edi-scraper-php:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
        environment:
            APP_ENV: ${APP_ENV}
        container_name: php-up-edi

#        For prod
#        command: composer run-script serve

# For prod
#networks:
#    walmart_scraper_network:
#        external: true
#        name: walmart_scraper_network