name: Tests

on:
  pull_request:
    branches: [dev, stage, main]
  push:
    branches: [main, feature/*, hotfix/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker compose --env-file .env.test \
            -f docker-compose.yml \
            -f docker/config-envs/test/docker-compose.override.yml \
            build

      - name: Start container
        run: |
          docker compose --env-file .env.test \
            -f docker-compose.yml \
            -f docker/config-envs/test/docker-compose.override.yml \
            up -d

      - name: Run tests
        run: |
          docker compose --env-file .env.test \
            -f docker-compose.yml \
            -f docker/config-envs/test/docker-compose.override.yml \
            exec -T php-up-edi php vendor/bin/phpunit --coverage-text --colors=always --testdox

      - name: Cleanup
        if: always()
        run: |
          docker compose --env-file .env.test \
            -f docker-compose.yml \
            -f docker/config-envs/test/docker-compose.override.yml \
            down -v
